package com.uniserve.adapters.email;

import com.uniserve.adapters.ChannelMessageReceived;
import jakarta.mail.Session;
import jakarta.mail.internet.MimeMessage;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Unit tests for email MIME parsing (Feature 02a) — no IMAP server required. */
class EmailAdapterParseTest {

    private static MimeMessage mime(String raw) throws Exception {
        Session session = Session.getInstance(new Properties());
        return new MimeMessage(session, new ByteArrayInputStream(raw.getBytes(StandardCharsets.UTF_8)));
    }

    @Test
    void extractsFromAddressAsUnverifiedEmailIdentity() throws Exception {
        MimeMessage msg = mime("""
                From: John <john@example.com>
                Subject: Billing
                Message-ID: <m1@example.com>
                Content-Type: text/plain; charset=UTF-8

                My bill is wrong""");

        ChannelMessageReceived event = EmailAdapter.parseMessage(msg, "default");

        assertEquals("email", event.channelIdentity().type());
        assertEquals("john@example.com", event.channelIdentity().value());
        assertFalse(event.channelIdentity().verified(), "email identity is never natively verified");
        assertEquals("My bill is wrong", event.rawText());
    }

    @Test
    void stripsHtmlToPlainText() throws Exception {
        MimeMessage msg = mime("""
                From: jane@example.com
                Subject: HTML
                Content-Type: text/html; charset=UTF-8

                <html><body><p>Hello <b>world</b></p><p>My&nbsp;bill is wrong</p></body></html>""");

        ChannelMessageReceived event = EmailAdapter.parseMessage(msg, "default");

        String text = event.rawText();
        assertFalse(text.contains("<"), "tags should be stripped: " + text);
        assertTrue(text.contains("Hello world"), text);
        assertTrue(text.contains("My bill is wrong"), text);
    }

    @Test
    void replyEmailThreadIdMatchesParentMessageId() throws Exception {
        MimeMessage msg = mime("""
                From: john@example.com
                Subject: Re: Billing
                Message-ID: <reply-2@example.com>
                In-Reply-To: <parent-1@example.com>
                References: <parent-1@example.com>
                Content-Type: text/plain; charset=UTF-8

                Following up""");

        ChannelMessageReceived event = EmailAdapter.parseMessage(msg, "default");

        assertEquals("parent-1@example.com", event.threadId());
        assertEquals("parent-1@example.com", event.inReplyTo());
    }

    @Test
    void newEmailWithoutThreadingHeadersHasNullThreadId() throws Exception {
        MimeMessage msg = mime("""
                From: new@example.com
                Subject: New
                Message-ID: <new-1@example.com>
                Content-Type: text/plain; charset=UTF-8

                Brand new conversation""");

        ChannelMessageReceived event = EmailAdapter.parseMessage(msg, "default");
        assertEquals(null, event.threadId());
    }

    // ---- auto-generated mail detection (UI_REVAMP follow-up: bounces must not become tickets) ----

    @Test
    void flagsMailerDaemonBounceAsAutoGenerated() throws Exception {
        MimeMessage msg = mime("""
                From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
                Subject: Delivery Status Notification (Failure)
                Content-Type: text/plain; charset=UTF-8

                The email to anon@example.com was not delivered.""");
        assertTrue(EmailAdapter.isAutoGenerated(msg));
    }

    @Test
    void flagsAutoSubmittedHeaderAndOutOfOffice() throws Exception {
        MimeMessage autoSubmitted = mime("""
                From: citizen@gmail.com
                Subject: Re: your ticket
                Auto-Submitted: auto-replied
                Content-Type: text/plain; charset=UTF-8

                I am away.""");
        assertTrue(EmailAdapter.isAutoGenerated(autoSubmitted));

        MimeMessage ooo = mime("""
                From: citizen@gmail.com
                Subject: Automatic reply: power cut
                Content-Type: text/plain; charset=UTF-8

                Out of office.""");
        assertTrue(EmailAdapter.isAutoGenerated(ooo));

        MimeMessage noreply = mime("""
                From: forwarding-noreply@google.com
                Subject: Gmail Forwarding Confirmation
                Content-Type: text/plain; charset=UTF-8

                Confirmation code.""");
        assertTrue(EmailAdapter.isAutoGenerated(noreply));
    }

    @Test
    void realComplaintsAreNotFlagged() throws Exception {
        MimeMessage msg = mime("""
                From: Nithin <nithin@gmail.com>
                Subject: Meter not working
                Content-Type: text/plain; charset=UTF-8

                Please have someone check it.""");
        assertFalse(EmailAdapter.isAutoGenerated(msg));

        MimeMessage reply = mime("""
                From: citizen@gmail.com
                Subject: Re: [Ticket TKT-00042] any update?
                Content-Type: text/plain; charset=UTF-8

                Checking on status.""");
        assertFalse(EmailAdapter.isAutoGenerated(reply));
    }
}
