package com.uniserve.adapters.email;

import com.uniserve.adapters.ChannelIdentity;
import com.uniserve.adapters.ChannelMessagePublisher;
import com.uniserve.adapters.ChannelMessageReceived;
import com.uniserve.adapters.EventValidator;
import io.quarkus.mailer.Mail;
import io.quarkus.mailer.Mailer;
import io.quarkus.scheduler.Scheduled;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.mail.Flags;
import jakarta.mail.Folder;
import jakarta.mail.Message;
import jakarta.mail.Multipart;
import jakarta.mail.Part;
import jakarta.mail.Session;
import jakarta.mail.Store;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.search.FlagTerm;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.Properties;
import java.util.UUID;

/**
 * Email channel adapter (Feature 02a): polls a mailbox over IMAP, normalises each
 * message to the canonical {@link ChannelMessageReceived} event, and sends
 * outbound replies over SMTP (via the Quarkus mailer). Both directions use the
 * same Gmail App Password — App Passwords cover IMAP as well as SMTP once
 * 2-Step Verification is enabled (see docs/02a_ADAPTER_EMAIL.md's Phase 1 notes).
 *
 * <p>Identity is always {@code email / verified=false}, so the downstream identity
 * gate triggers. Parsing ({@link #parseMessage}) is pure and unit-tested; IMAP
 * connectivity is skipped when no host is configured.
 */
@ApplicationScoped
public class EmailAdapter {

    private static final Logger LOG = Logger.getLogger(EmailAdapter.class);

    @Inject
    ChannelMessagePublisher publisher;

    @Inject
    Mailer mailer;

    // Optional<String>: SmallRye treats an empty value as absent, so "unconfigured"
    // (dev default) becomes Optional.empty() instead of failing String conversion.
    @ConfigProperty(name = "email.imap.host")
    Optional<String> imapHost;

    @ConfigProperty(name = "email.imap.port", defaultValue = "993")
    int imapPort;

    @ConfigProperty(name = "email.imap.user")
    Optional<String> imapUser;

    @ConfigProperty(name = "email.imap.password")
    Optional<String> imapPassword;

    @ConfigProperty(name = "email.imap.mailbox", defaultValue = "INBOX")
    String mailbox;

    @ConfigProperty(name = "gateway.tenant-id", defaultValue = "default")
    String tenantId;

    /** Result of a poll cycle. */
    public record PollResult(int messagesProcessed, int errors) {
    }

    private boolean imapConfigured() {
        return imapHost.filter(h -> !h.isBlank()).isPresent();
    }

    @Scheduled(every = "{email.poll.interval}")
    void scheduledPoll() {
        if (!imapConfigured()) {
            return; // no mailbox configured (dev default) — nothing to poll
        }
        try {
            PollResult result = pollOnce();
            LOG.infof("Email poll: processed=%d errors=%d", result.messagesProcessed(), result.errors());
        } catch (Exception e) {
            LOG.errorf(e, "Scheduled email poll failed");
        }
    }

    /**
     * Poll the mailbox once for unseen messages. Returns 0/0 when IMAP is not
     * configured (dev) so the manual-poll endpoint stays usable without a server.
     */
    public PollResult pollOnce() {
        if (!imapConfigured()) {
            return new PollResult(0, 0);
        }

        int processed = 0;
        int errors = 0;
        Store store = null;
        Folder folder = null;
        try {
            Properties props = new Properties();
            props.put("mail.store.protocol", "imaps");
            Session session = Session.getInstance(props);
            store = session.getStore("imaps");
            store.connect(imapHost.get(), imapPort, imapUser.orElse(""), imapPassword.orElse(""));

            folder = store.getFolder(mailbox);
            folder.open(Folder.READ_WRITE);

            Message[] unseen = folder.search(new FlagTerm(new Flags(Flags.Flag.SEEN), false));
            for (Message message : unseen) {
                try {
                    // Bounces, out-of-office, and other machine-generated mail must
                    // never become tickets (a Gmail DSN once got filed as a
                    // "technical complaint" with mailer-daemon as the citizen).
                    if (isAutoGenerated(message)) {
                        LOG.infof("Skipping auto-generated email: from=%s subject=%s",
                                extractFrom(message), message.getSubject());
                        message.setFlag(Flags.Flag.SEEN, true);
                        continue;
                    }
                    ChannelMessageReceived event = parseMessage(message, tenantId);
                    LOG.infof("Email message received: traceId=%s from=%s threadId=%s",
                            event.traceId(), event.channelIdentity().value(), event.threadId());
                    List<String> validationErrors = EventValidator.validate(event);
                    if (!validationErrors.isEmpty()) {
                        errors++;
                        LOG.warnf("Skipping invalid parsed email: traceId=%s errors=%s",
                                event.traceId(), validationErrors);
                    } else {
                        publisher.publish(event);
                        processed++;
                    }
                    message.setFlag(Flags.Flag.SEEN, true);
                } catch (Exception e) {
                    errors++;
                    LOG.errorf(e, "Failed to process email message");
                }
            }
        } catch (Exception e) {
            errors++;
            LOG.errorf(e, "IMAP poll failed for host %s", imapHost);
        } finally {
            closeQuietly(folder);
            closeQuietly(store);
        }
        return new PollResult(processed, errors);
    }

    /** Send an outbound reply over SMTP. Returns true when no exception is thrown. */
    public boolean sendReply(String toAddress, String subject, String body, String inReplyToMessageId) {
        Mail mail = Mail.withText(toAddress, subject, body);
        if (!isBlank(inReplyToMessageId)) {
            mail.addHeader("In-Reply-To", inReplyToMessageId);
            mail.addHeader("References", inReplyToMessageId);
        }
        mailer.send(mail);
        LOG.infof("Email reply sent to=%s subject=%s", toAddress, subject);
        return true;
    }

    // ---- auto-generated mail detection (pure, unit-tested) ---------------

    private static final java.util.regex.Pattern AUTO_SENDER = java.util.regex.Pattern.compile(
            "^(mailer-daemon|postmaster|bounce[s]?)@|(^|[.+-])(no-?reply|do-?not-?reply|donotreply|auto-?reply)@"
                    + "|-noreply@|noreply[.-]",
            java.util.regex.Pattern.CASE_INSENSITIVE);

    private static final java.util.regex.Pattern AUTO_SUBJECT = java.util.regex.Pattern.compile(
            "delivery status notification|undeliver(able|ed)|mail delivery (failed|failure|subsystem)"
                    + "|returned mail|failure notice|delivery has failed|automatic reply|auto[- ]?reply"
                    + "|autoreply|out of (the )?office|vacation notice",
            java.util.regex.Pattern.CASE_INSENSITIVE);

    /**
     * True for machine-generated mail that must not enter the complaint
     * pipeline: RFC 3834 {@code Auto-Submitted}, auto-responder headers, bulk
     * precedence, DSN report content-types, null return-path bounces,
     * mailer-daemon/no-reply senders, and classic bounce/OOO subjects.
     */
    static boolean isAutoGenerated(Message message) {
        try {
            String[] autoSubmitted = message.getHeader("Auto-Submitted");
            if (autoSubmitted != null && autoSubmitted.length > 0
                    && !"no".equalsIgnoreCase(autoSubmitted[0].trim())) {
                return true;
            }
            if (message.getHeader("X-Autoreply") != null || message.getHeader("X-Autorespond") != null
                    || message.getHeader("X-Failed-Recipients") != null) {
                return true;
            }
            String[] precedence = message.getHeader("Precedence");
            if (precedence != null && precedence.length > 0) {
                String p = precedence[0].trim();
                if ("bulk".equalsIgnoreCase(p) || "junk".equalsIgnoreCase(p) || "auto_reply".equalsIgnoreCase(p)) {
                    return true;
                }
            }
            String[] returnPath = message.getHeader("Return-Path");
            if (returnPath != null && returnPath.length > 0 && "<>".equals(returnPath[0].trim())) {
                return true;
            }
            String contentType = message.getContentType();
            if (contentType != null && contentType.toLowerCase().startsWith("multipart/report")) {
                return true;
            }
            String from = extractFrom(message);
            if (from != null && AUTO_SENDER.matcher(from).find()) {
                return true;
            }
            String subject = message.getSubject();
            return subject != null && AUTO_SUBJECT.matcher(subject).find();
        } catch (Exception e) {
            // When in doubt, let it through — a lost complaint is worse than a junk ticket.
            return false;
        }
    }

    // ---- parsing (pure, unit-tested) -------------------------------------

    static ChannelMessageReceived parseMessage(Message message, String tenantId) throws Exception {
        String from = extractFrom(message);
        String rawText = extractText(message);
        String threadId = extractThreadId(message);
        String messageId = extractMessageId(message);
        String subject = message.getSubject();
        String nowIso = Instant.now().toString();
        String sentAt = message.getSentDate() != null
                ? message.getSentDate().toInstant().toString() : nowIso;

        return new ChannelMessageReceived(
                UUID.randomUUID().toString(),
                tenantId,
                ChannelMessageReceived.TYPE,
                nowIso,
                "email",
                new ChannelIdentity("email", from, false),
                rawText,
                List.of(),
                null,               // languageHint
                threadId,
                threadId,           // inReplyTo == parent message id
                sentAt,
                nowIso,
                UUID.randomUUID().toString(),
                subject,
                messageId);
    }

    static String extractFrom(Message message) throws Exception {
        if (message.getFrom() == null || message.getFrom().length == 0) {
            return null;
        }
        return ((InternetAddress) message.getFrom()[0]).getAddress();
    }

    /** In-Reply-To (or first References id), angle brackets stripped; null if none. */
    static String extractThreadId(Message message) throws Exception {
        String[] inReplyTo = message.getHeader("In-Reply-To");
        if (inReplyTo != null && inReplyTo.length > 0 && !isBlank(inReplyTo[0])) {
            return stripBrackets(inReplyTo[0].trim());
        }
        String[] references = message.getHeader("References");
        if (references != null && references.length > 0 && !isBlank(references[0])) {
            String[] ids = references[0].trim().split("\\s+");
            return stripBrackets(ids[ids.length - 1]);
        }
        return null;
    }

    /** This message's OWN Message-ID (Feature 15) — distinct from {@link #extractThreadId},
     * which reads the PARENT's id. Used so our replies can thread back to this exact message. */
    static String extractMessageId(Message message) throws Exception {
        String[] messageId = message.getHeader("Message-ID");
        if (messageId != null && messageId.length > 0 && !isBlank(messageId[0])) {
            return stripBrackets(messageId[0].trim());
        }
        return null;
    }

    static String extractText(Part part) throws Exception {
        Object content = part.getContent();
        if (part.isMimeType("text/plain")) {
            return ((String) content).trim();
        }
        if (part.isMimeType("text/html")) {
            return htmlToText((String) content);
        }
        if (content instanceof Multipart multipart) {
            String htmlFallback = null;
            for (int i = 0; i < multipart.getCount(); i++) {
                Part bodyPart = multipart.getBodyPart(i);
                if (bodyPart.isMimeType("text/plain")) {
                    return ((String) bodyPart.getContent()).trim();
                }
                if (bodyPart.isMimeType("text/html")) {
                    htmlFallback = htmlToText((String) bodyPart.getContent());
                } else if (bodyPart.getContent() instanceof Multipart) {
                    String nested = extractText(bodyPart);
                    if (nested != null && !nested.isBlank()) {
                        return nested;
                    }
                }
            }
            return htmlFallback;
        }
        return content == null ? null : content.toString().trim();
    }

    /** Minimal HTML → text: drop tags, unescape common entities, collapse whitespace. */
    static String htmlToText(String html) {
        if (html == null) {
            return null;
        }
        String text = html
                .replaceAll("(?is)<(script|style)[^>]*>.*?</\\1>", " ")
                .replaceAll("(?i)<br\\s*/?>", "\n")
                .replaceAll("(?i)</p>", "\n")
                .replaceAll("<[^>]+>", "");
        text = text
                .replace("&nbsp;", " ")
                .replace("&amp;", "&")
                .replace("&lt;", "<")
                .replace("&gt;", ">")
                .replace("&quot;", "\"")
                .replace("&#39;", "'");
        return text.replaceAll("[ \\t]+", " ").replaceAll("\\n{2,}", "\n").trim();
    }

    private static String stripBrackets(String id) {
        return id.replaceAll("^<|>$", "");
    }

    private static boolean isBlank(String s) {
        return s == null || s.isBlank();
    }

    private void closeQuietly(Folder folder) {
        try {
            if (folder != null && folder.isOpen()) {
                folder.close(false);
            }
        } catch (Exception ignored) {
            // best effort
        }
    }

    private void closeQuietly(Store store) {
        try {
            if (store != null && store.isConnected()) {
                store.close();
            }
        } catch (Exception ignored) {
            // best effort
        }
    }
}
